/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all users */
        get: operations["ListUsers"];
        put?: never;
        /** @description Create a new user */
        post: operations["CreateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a user by ID */
        get: operations["GetUser"];
        /** @description Update a user */
        put: operations["UpdateUser"];
        post?: never;
        /** @description Delete a user */
        delete: operations["DeleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}/lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListTodoLists"];
        put?: never;
        /** @description TodoList operations */
        post: operations["CreateTodoList"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}/lists/{listId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetTodoList"];
        put: operations["UpdateTodoList"];
        post?: never;
        delete: operations["DeleteTodoList"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}/lists/{listId}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListTodoTasks"];
        put?: never;
        /** @description TodoTask operations */
        post: operations["CreateTodoTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}/lists/{listId}/tasks/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetTodoTask"];
        put: operations["UpdateTodoTask"];
        post?: never;
        delete: operations["DeleteTodoTask"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ConflictExceptionResponseContent: {
            message: string;
        };
        /** @description TodoList structures */
        CreateTodoListRequestContent: {
            name: string;
            description?: string;
        };
        CreateTodoListResponseContent: {
            /** @description User identifier */
            userId: string;
            /** @description Identifiers */
            listId: string;
            name: string;
            description?: string;
            /** Format: double */
            createdAt: number;
            /** Format: double */
            updatedAt: number;
        };
        /** @description TodoTask structures */
        CreateTodoTaskRequestContent: {
            description: string;
            /** @default false */
            completed: boolean;
            order?: number;
        };
        CreateTodoTaskResponseContent: {
            /** @description User identifier */
            userId: string;
            /** @description Identifiers */
            listId: string;
            taskId: string;
            description: string;
            completed: boolean;
            order?: number;
            /** Format: double */
            createdAt: number;
            /** Format: double */
            updatedAt: number;
        };
        /** @description Structure for creating a new user */
        CreateUserRequestContent: {
            username: string;
            email: string;
        };
        /** @description Structure for user response */
        CreateUserResponseContent: {
            /** @description User identifier */
            userId: string;
            username: string;
            email: string;
            /** Format: double */
            createdAt: number;
        };
        GetTodoListResponseContent: {
            /** @description User identifier */
            userId: string;
            /** @description Identifiers */
            listId: string;
            name: string;
            description?: string;
            /** Format: double */
            createdAt: number;
            /** Format: double */
            updatedAt: number;
        };
        GetTodoTaskResponseContent: {
            /** @description User identifier */
            userId: string;
            /** @description Identifiers */
            listId: string;
            taskId: string;
            description: string;
            completed: boolean;
            order?: number;
            /** Format: double */
            createdAt: number;
            /** Format: double */
            updatedAt: number;
        };
        /** @description Structure for user response */
        GetUserResponseContent: {
            /** @description User identifier */
            userId: string;
            username: string;
            email: string;
            /** Format: double */
            createdAt: number;
        };
        ListTodoListsResponseContent: {
            lists: components["schemas"]["TodoListOutput"][];
            nextToken?: string;
        };
        ListTodoTasksResponseContent: {
            tasks: components["schemas"]["TodoTaskOutput"][];
            nextToken?: string;
        };
        ListUsersResponseContent: {
            users: components["schemas"]["UserOutput"][];
            nextToken?: string;
        };
        ResourceNotFoundExceptionResponseContent: {
            message: string;
        };
        TodoListOutput: {
            /** @description User identifier */
            userId: string;
            /** @description Identifiers */
            listId: string;
            name: string;
            description?: string;
            /** Format: double */
            createdAt: number;
            /** Format: double */
            updatedAt: number;
        };
        TodoTaskOutput: {
            /** @description User identifier */
            userId: string;
            /** @description Identifiers */
            listId: string;
            taskId: string;
            description: string;
            completed: boolean;
            order?: number;
            /** Format: double */
            createdAt: number;
            /** Format: double */
            updatedAt: number;
        };
        UpdateTodoListRequestContent: {
            name?: string;
            description?: string;
        };
        UpdateTodoListResponseContent: {
            /** @description User identifier */
            userId: string;
            /** @description Identifiers */
            listId: string;
            name: string;
            description?: string;
            /** Format: double */
            createdAt: number;
            /** Format: double */
            updatedAt: number;
        };
        UpdateTodoTaskRequestContent: {
            description?: string;
            completed?: boolean;
            order?: number;
        };
        UpdateTodoTaskResponseContent: {
            /** @description User identifier */
            userId: string;
            /** @description Identifiers */
            listId: string;
            taskId: string;
            description: string;
            completed: boolean;
            order?: number;
            /** Format: double */
            createdAt: number;
            /** Format: double */
            updatedAt: number;
        };
        /** @description Structure for updating a user */
        UpdateUserRequestContent: {
            username?: string;
            email?: string;
        };
        /** @description Structure for user response */
        UpdateUserResponseContent: {
            /** @description User identifier */
            userId: string;
            username: string;
            email: string;
            /** Format: double */
            createdAt: number;
        };
        /** @description Structure for user response */
        UserOutput: {
            /** @description User identifier */
            userId: string;
            username: string;
            email: string;
            /** Format: double */
            createdAt: number;
        };
        /** @description Common error structures */
        ValidationExceptionResponseContent: {
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ListUsers: {
        parameters: {
            query?: {
                maxResults?: number;
                nextToken?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ListUsers 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListUsersResponseContent"];
                };
            };
        };
    };
    CreateUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequestContent"];
            };
        };
        responses: {
            /** @description CreateUser 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateUserResponseContent"];
                };
            };
            /** @description ValidationException 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationExceptionResponseContent"];
                };
            };
            /** @description ConflictException 409 response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictExceptionResponseContent"];
                };
            };
        };
    };
    GetUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User identifier */
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GetUser 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetUserResponseContent"];
                };
            };
            /** @description ValidationException 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationExceptionResponseContent"];
                };
            };
            /** @description ResourceNotFoundException 404 response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceNotFoundExceptionResponseContent"];
                };
            };
        };
    };
    UpdateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User identifier */
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequestContent"];
            };
        };
        responses: {
            /** @description UpdateUser 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateUserResponseContent"];
                };
            };
            /** @description ValidationException 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationExceptionResponseContent"];
                };
            };
            /** @description ResourceNotFoundException 404 response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceNotFoundExceptionResponseContent"];
                };
            };
        };
    };
    DeleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User identifier */
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DeleteUser 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ValidationException 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationExceptionResponseContent"];
                };
            };
            /** @description ResourceNotFoundException 404 response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceNotFoundExceptionResponseContent"];
                };
            };
        };
    };
    ListTodoLists: {
        parameters: {
            query?: {
                maxResults?: number;
                nextToken?: string;
            };
            header?: never;
            path: {
                /** @description User identifier */
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ListTodoLists 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListTodoListsResponseContent"];
                };
            };
        };
    };
    CreateTodoList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User identifier */
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTodoListRequestContent"];
            };
        };
        responses: {
            /** @description CreateTodoList 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTodoListResponseContent"];
                };
            };
            /** @description ValidationException 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationExceptionResponseContent"];
                };
            };
            /** @description ResourceNotFoundException 404 response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceNotFoundExceptionResponseContent"];
                };
            };
        };
    };
    GetTodoList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User identifier */
                userId: string;
                /** @description Identifiers */
                listId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GetTodoList 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetTodoListResponseContent"];
                };
            };
            /** @description ValidationException 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationExceptionResponseContent"];
                };
            };
            /** @description ResourceNotFoundException 404 response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceNotFoundExceptionResponseContent"];
                };
            };
        };
    };
    UpdateTodoList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User identifier */
                userId: string;
                /** @description Identifiers */
                listId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateTodoListRequestContent"];
            };
        };
        responses: {
            /** @description UpdateTodoList 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateTodoListResponseContent"];
                };
            };
            /** @description ValidationException 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationExceptionResponseContent"];
                };
            };
            /** @description ResourceNotFoundException 404 response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceNotFoundExceptionResponseContent"];
                };
            };
        };
    };
    DeleteTodoList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User identifier */
                userId: string;
                /** @description Identifiers */
                listId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DeleteTodoList 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ValidationException 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationExceptionResponseContent"];
                };
            };
            /** @description ResourceNotFoundException 404 response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceNotFoundExceptionResponseContent"];
                };
            };
        };
    };
    ListTodoTasks: {
        parameters: {
            query?: {
                maxResults?: number;
                nextToken?: string;
                completed?: boolean;
            };
            header?: never;
            path: {
                /** @description User identifier */
                userId: string;
                /** @description Identifiers */
                listId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ListTodoTasks 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListTodoTasksResponseContent"];
                };
            };
        };
    };
    CreateTodoTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User identifier */
                userId: string;
                /** @description Identifiers */
                listId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTodoTaskRequestContent"];
            };
        };
        responses: {
            /** @description CreateTodoTask 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTodoTaskResponseContent"];
                };
            };
            /** @description ValidationException 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationExceptionResponseContent"];
                };
            };
            /** @description ResourceNotFoundException 404 response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceNotFoundExceptionResponseContent"];
                };
            };
        };
    };
    GetTodoTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User identifier */
                userId: string;
                /** @description Identifiers */
                listId: string;
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GetTodoTask 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetTodoTaskResponseContent"];
                };
            };
            /** @description ValidationException 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationExceptionResponseContent"];
                };
            };
            /** @description ResourceNotFoundException 404 response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceNotFoundExceptionResponseContent"];
                };
            };
        };
    };
    UpdateTodoTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User identifier */
                userId: string;
                /** @description Identifiers */
                listId: string;
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateTodoTaskRequestContent"];
            };
        };
        responses: {
            /** @description UpdateTodoTask 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateTodoTaskResponseContent"];
                };
            };
            /** @description ValidationException 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationExceptionResponseContent"];
                };
            };
            /** @description ResourceNotFoundException 404 response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceNotFoundExceptionResponseContent"];
                };
            };
        };
    };
    DeleteTodoTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User identifier */
                userId: string;
                /** @description Identifiers */
                listId: string;
                taskId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DeleteTodoTask 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ValidationException 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationExceptionResponseContent"];
                };
            };
            /** @description ResourceNotFoundException 404 response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceNotFoundExceptionResponseContent"];
                };
            };
        };
    };
}
